### ISSUE TITLE
Add new command to remove empty columns

### ISSUE THREAD

**Issue by SimonGreenhill** [glottobank/pygrambank#10]

**Comment by xrotwang** [comment]
I think, ideally, this should be part of **one** biggish command (incorporating `grambank recode`), fixing all that's wrong with a newly submitted sheet - possibly interactively. For everything already in the repos, `grambank check` should make sure there are no empty columns (which is not the case right now).

**Comment by SimonGreenhill** [comment]
Ok, since I'd already mainly implemented this, and it made my life easier I've packaged it as a PR. Perhaps this can get rolled into a 'fix' command later?

**Comment by SimonGreenhill** [comment]
see #11
