### ISSUE TITLE
Make language metadata more complete

### ISSUE THREAD

**Issue by xrotwang** [glottobank/pygrambank#3]
See https://github.com/glottobank/grambank-cldf/issues/8

**Comment by xrotwang** [comment]
Now that the data in question is available as [CLDF dataset](https://doi.org/10.5281/zenodo.3260728), we shouldn't include this data in the Grambank release anymore, but just require the Glottolog CLDF dataset as additional data source.

@SimonGreenhill @HedvigS this will require changes in the data processing code.

**Comment by HedvigS** [comment]
Right, terrific. Now to figure out how the best incorporate that into the workflow. I'll get on that when I have time.
