### ISSUE TITLE
subcommand to create an empty sheet

### ISSUE THREAD

**Issue by xrotwang** [glottobank/pygrambank#7]
see https://github.com/glottobank/Grambank/issues/308

**Comment by HedvigS** [comment]
[(Potentially with the empty column "contributed_datapoints")](https://github.com/glottobank/Grambank/issues/228)

**Comment by HedvigS** [comment]
Is this working as planned now, populating grambank/For_coders with a tsv sheet? 

If so, we should remove

```
GramBank_most_updated_sheet.xlsx
GramBank_most_updated_sheet-21-Dec-2017.xlsx
GramBank_most_updated_sheet-20-Aug-2018.xlsx
GramBank_most_updated_sheet-11-Nov-2017.xlsx
```

**Comment by xrotwang** [comment]
Well, as far as I can see nobody used a sheet created by this command yet - so I don't know if it's working as planned. The command could also become more comfortable, e.g. filling in `Language_ID` automatically, which it isn't doing at the moment.

**Comment by HedvigS** [comment]
I'm sorry, I don't understand. There is no tsv-sheet in for_coders of this kind. I thought you meant that the cldf-function would populate the for_coders sheet with an updated sheet with the latest summaries form the wiki. 

No coder has been told to look for empty sheets anywhere else but in the For_coders folder.

**Comment by HedvigS** [comment]
I don't think we can expect our coders to use `pygrambank`.

**Comment by xrotwang** [comment]
I see. Can you do this? What info from the wiki should go into the sheet?

**Comment by HedvigS** [comment]
I'm sorry, no I cannot to this, at least not now.  I thought that the PR you made would do this, but we were misunderstanding each other.

The info from the wiki per feature that should go into the sheet is the section with the title "Summary". This section is marked as

`##Summary`

In all the relevant wiki pages and there is always a section called "## Procedure" right after.

**Comment by HedvigS** [comment]
Coders do use these cells for fast look up while they're coding, especially if they're in a place with no internet. We'd have to poll them to find out how a change like that would be received.

@alenawitzlack @tobiaskweber @Jaylatarche @RobHerrera do you think it'd be a good idea to remove the columns "Summary" and "Clarifying comments" from the empty "most up to date" sheet and rely entirely on the wiki?

**Comment by xrotwang** [comment]
Ok. Leaving this info in is not a problem on my side. "Summary" and
"Clarifying comments" is the same thing, though.

Hedvig Skirgård <notifications@github.com> schrieb am Sa., 5. Okt. 2019,
02:01:

**Comment by HedvigS** [comment]
Leaving that info in would be better then, thanks.

Ah, sorry. Harald has been populating "Clarifying comments" with "Summary". They used to be different things but now aren't. All good, thanks!

Just so we're on the same page, the columns in this empty sheet should be

- Language_ID
- Grambank_ID
- Possible Values
- Value
- Source
- Comment
- Contributed_datapoints
- Clarifying comments
- Relevant unit(s) 
- Function 
- Form 

[We could also add in Eri's order which some people like for convenience during coding.
](https://github.com/glottobank/Grambank/blob/master/For_coders/Grambank_feature_groupings/for_coding/Grambank_Eri_order.xlsx).

Does that sound alright?
