### ISSUE TITLE
pygrambank check output different

### ISSUE THREAD

**Issue by HedvigS** [glottobank/pygrambank#8]
The check command used to output a col called "selected", it doesn't seem to do so anymore. Yesterday, @chrzyki helped me run pygrambank. We had to reinstall various things  

It may be that the command I ran is somehow still an outdated version.

For example, HJH_mort1237 and MH_mort1237 both contain lots of errors, but the sheet that was actually selected for this language was coded by @d97hah and has no automatic errors.

I've made some changes to the r-script so that it can take the new check output, but since there's not information on selected I can't run it yet and update the relevant lists. The current version of the script is here:
https://github.com/glottobank/Grambank/compare/script_to_update?expand=1

**Comment by xrotwang** [comment]
Passing `--report report.tsv` to the `check` command should give you what you want:

```shell script
$ grambank check -husage: grambank check [-h] [--report REPORT]

Check original_sheets/ for correctness.

optional arguments:
  -h, --help       show this help message and exit
  --report REPORT  Path of TSV file, to which results will be written.
                   (default: None)
```

**Comment by HedvigS** [comment]
Right okay. I didn't know there had been a change. What's the easiest way to stay up to date with changes of this kind?

**Comment by xrotwang** [comment]
Switching to a new way of organizing the cli will not happen again any time soon. So changes of this kind are rare. But whenever you update a package (which you did with `pygrambank`), and then experience differences in behaviour, you'd check the version number:
```python
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygrambank
>>> pygrambank.__version__
'1.0.1.dev0'
```
and if the major version changed, differences are to be expected (i.e. you'd have to relearn the behaviour, e.g. reading the cli help); if not, you'd file an issue.

**Comment by HedvigS** [comment]
Okay, right. 

So far, I've only ever needed one command in pygrambank - check. This change seems to be a reversion to a previous state of the command rather than a change to something new, and the cli help documentation didn't specify that the command line output was no longer the same, and that the report file was different from what's shown on the console. If there are changes like this in other commands in these projects, chances are I'll trial and error it and if that doesn't work I'll be filing issues. If that's alright, then it'll be fine.
